import React, { useState } from 'react';
import { Copy, Download, CheckCircle2 } from 'lucide-react';
import { TruthGuardAnalysis, Language } from '../types';

interface EvidencePackProps {
  analysis: TruthGuardAnalysis;
  language?: Language;
  isSeniorMode?: boolean;
}

const TRANSLATIONS = {
  en: {
    title: 'Evidence / report pack',
    subtitle: 'Copy or download a structured summary for family, police, your bank, or a platform report form.',
    copy: 'Copy to Clipboard',
    copied: 'Copied!',
    download: 'Download as .txt',
    analysisHeader: '=== VerifyFirst AI — Evidence & Reporting Pack ===',
    input: 'Input Analyzed',
    type: 'Input Type',
    scamScore: 'Scam Probability',
    verdict: 'Verdict',
    riskSignals: 'Risk Signals Detected',
    timestamp: 'Analyzed At',
    footer: 'Generated by verify1st.tw',
  },
  'zh-TW': {
    title: '證據 / 回報包',
    subtitle: '複製或下載整理過的摘要，拿去給家人、165、平台檢舉或銀行都比較方便。',
    copy: '複製到剪貼簿',
    copied: '已複製！',
    download: '下載 .txt 檔案',
    analysisHeader: '=== VerifyFirst AI — 證據與回報摘要 ===',
    input: '分析對象',
    type: '輸入類型',
    scamScore: '詐騙機率',
    verdict: '判定結果',
    riskSignals: '偵測到的風險訊號',
    timestamp: '分析時間',
    footer: '由 verify1st.tw 生成',
  },
  vi: {
    title: 'Gói bằng chứng / báo cáo',
    subtitle: 'Sao chép hoặc tải xuống bản tóm tắt có cấu trúc để gửi cho gia đình, cảnh sát, ngân hàng hoặc nền tảng.',
    copy: 'Sao chép vào clipboard',
    copied: 'Đã sao chép!',
    download: 'Tải xuống .txt',
    analysisHeader: '=== VerifyFirst AI — Gói bằng chứng & báo cáo ===',
    input: 'Đầu vào được phân tích',
    type: 'Loại đầu vào',
    scamScore: 'Xác suất lừa đảo',
    verdict: 'Phán quyết',
    riskSignals: 'Tín hiệu rủi ro được phát hiện',
    timestamp: 'Được phân tích lúc',
    footer: 'Được tạo bởi verify1st.tw',
  },
};

function buildEvidenceText(analysis: TruthGuardAnalysis, t: typeof TRANSLATIONS.en): string {
  const lines: string[] = [
    t.analysisHeader,
    '',
    `${t.input}: ${analysis.originalInput}`,
    `${t.type}: ${analysis.inputType}`,
    `${t.scamScore}: ${analysis.scamProbability}%`,
    `${t.verdict}: ${analysis.verdict ?? analysis.seniorModeVerdict ?? 'N/A'}`,
    `${t.timestamp}: ${new Date().toLocaleString()}`,
    `Final verdict: ${analysis.finalVerdict}`,
    `Conclusion: ${analysis.conclusion}`,
    '',
    `${t.riskSignals}:`,
  ];

  if (analysis.riskSignals && analysis.riskSignals.length > 0) {
    analysis.riskSignals.forEach((signal) => {
      lines.push(`  [${signal.level}] ${signal.type}: ${signal.evidence}`);
    });
  } else {
    lines.push('  (none)');
  }

  lines.push('');
  lines.push(`Official route: ${analysis.officialRoute.label || analysis.officialRoute.url || 'N/A'}`);
  lines.push(`Official route status: ${analysis.officialRoute.status}`);
  lines.push(`Official route rationale: ${analysis.officialRoute.rationale}`);

  if (analysis.agentVerification?.originalUrl) {
    lines.push('');
    lines.push(`Agent original URL: ${analysis.agentVerification.originalUrl}`);
    lines.push(`Agent final page: ${analysis.agentVerification.finalLandingPage || 'N/A'}`);
    lines.push(`Agent page title: ${analysis.agentVerification.pageTitle || 'N/A'}`);
    lines.push(`Agent redirect chain: ${analysis.agentVerification.redirectChain.join(' -> ') || 'N/A'}`);
  }

  lines.push('');
  lines.push(t.footer);
  return lines.join('\n');
}

const EvidencePack: React.FC<EvidencePackProps> = ({
  analysis,
  language = 'en',
  isSeniorMode = false,
}) => {
  const [copied, setCopied] = useState(false);
  const t = TRANSLATIONS[language as keyof typeof TRANSLATIONS] ?? TRANSLATIONS.en;

  const evidenceText = buildEvidenceText(analysis, t);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(evidenceText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: select text
    }
  };

  const handleDownload = () => {
    const blob = new Blob([evidenceText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `verifyfirst-evidence-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className={`border border-gray-700 rounded-2xl ${isSeniorMode ? 'p-6 mb-8' : 'p-5 mb-6'} bg-gray-900/40`}>
      <h3 className={`font-bold text-white mb-1 flex items-center gap-2 ${isSeniorMode ? 'text-2xl' : 'text-lg'}`}>
        📁 {t.title}
      </h3>
      <p className={`text-gray-400 mb-4 ${isSeniorMode ? 'text-lg' : 'text-sm'}`}>{t.subtitle}</p>

      <pre className={`bg-gray-950 rounded-lg p-3 text-gray-400 font-mono whitespace-pre-wrap break-all mb-4 overflow-auto max-h-48 ${isSeniorMode ? 'text-sm' : 'text-xs'}`}>
        {evidenceText}
      </pre>

      <div className="flex gap-3 flex-wrap">
        <button
          onClick={handleCopy}
          className={`flex items-center gap-2 font-semibold rounded-xl transition-colors ${
            copied
              ? 'bg-green-700 text-white'
              : 'bg-gray-700 hover:bg-gray-600 text-gray-200'
          } ${isSeniorMode ? 'px-6 py-3 text-lg' : 'px-4 py-2 text-sm'}`}
        >
          {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          {copied ? t.copied : t.copy}
        </button>
        <button
          onClick={handleDownload}
          className={`flex items-center gap-2 bg-gray-700 hover:bg-gray-600 text-gray-200 font-semibold rounded-xl transition-colors ${isSeniorMode ? 'px-6 py-3 text-lg' : 'px-4 py-2 text-sm'}`}
        >
          <Download className="w-4 h-4" />
          {t.download}
        </button>
      </div>
    </div>
  );
};

export default EvidencePack;
