import React, { useEffect, useRef, useState } from 'react';
import { X, Copy, CheckCircle2, ExternalLink, Flag } from 'lucide-react';
import { TruthGuardAnalysis, Language } from '../types';

interface ReportModalProps {
  analysis: TruthGuardAnalysis;
  language: Language;
  onClose: () => void;
}

const REPORT_URL = 'https://165.npa.gov.tw/#/report/call/02';

const T = {
  'zh-TW': {
    title: '向 165 提交檢舉',
    step1: '步驟 1 — 複製報告內容',
    step2: '步驟 2 — 前往 165 填寫表單',
    step3: '步驟 3 — 貼上後填入個資送出',
    step1Desc: '我們已幫你整理好檢舉資料，複製後貼到表單的「說明」欄位。',
    step2Desc: '點擊下方按鈕，在新分頁開啟 165 官方線上報案表單。',
    step3Desc: '在「詐騙手法說明」欄位貼上，填寫你的姓名、電話後即可送出。',
    copy: '複製報告內容',
    copied: '已複製！',
    openForm: '前往 165 填寫表單',
    preview: '預覽報告內容',
    close: '關閉',
    hint: '165 反詐騙專線亦可直接撥打，免費 24 小時服務。',
    reportHeader: '【VerifyFirst AI 詐騙檢舉報告】',
    labelProb: '詐騙機率',
    labelVerdict: '判定結果',
    labelConclusion: '分析結論',
    labelInput: '可疑內容',
    labelType: '輸入類型',
    labelSignals: '偵測到的風險訊號',
    labelTechInfo: '技術資訊（供警方參考）',
    labelFinalUrl: '最終網址',
    labelRedirect: '重定向路徑',
    labelFooter: '由 verify1st.tw 分析',
    inputTypeMap: { URL: '網址', SMS_TEXT: '簡訊 / 訊息', PHONE: '電話號碼', IMAGE: '截圖' },
    verdictMap: {
      A_MARKETING: '一般行銷',
      B_RISKY_MARKETING: '高壓行銷（有風險）',
      C_SUSPICIOUS_NEEDS_VERIFICATION: '可疑，建議驗證',
      D_HIGH_RISK_SCAM: '高風險詐騙',
    },
  },
  en: {
    title: 'Submit Report to 165 Anti-Fraud',
    step1: 'Step 1 — Copy the report',
    step2: 'Step 2 — Open the 165 form',
    step3: 'Step 3 — Paste + fill personal info',
    step1Desc: "We've pre-formatted a report. Copy it and paste into the form's description field.",
    step2Desc: 'Click below to open the official 165 online report form in a new tab.',
    step3Desc: 'Paste the report in the "description" field, fill in your name and phone number, then submit.',
    copy: 'Copy Report',
    copied: 'Copied!',
    openForm: 'Open 165 Report Form',
    preview: 'Report preview',
    close: 'Close',
    hint: 'You can also call 165 directly — free 24h anti-fraud hotline.',
    reportHeader: '=== VerifyFirst AI — Fraud Report ===',
    labelProb: 'Scam Probability',
    labelVerdict: 'Verdict',
    labelConclusion: 'Conclusion',
    labelInput: 'Suspicious content',
    labelType: 'Input type',
    labelSignals: 'Risk signals detected',
    labelTechInfo: 'Technical info (for investigators)',
    labelFinalUrl: 'Final landing URL',
    labelRedirect: 'Redirect chain',
    labelFooter: 'Generated by verify1st.tw',
    inputTypeMap: { URL: 'URL', SMS_TEXT: 'SMS / Message', PHONE: 'Phone number', IMAGE: 'Screenshot' },
    verdictMap: {
      A_MARKETING: 'Normal marketing',
      B_RISKY_MARKETING: 'Risky marketing tactics',
      C_SUSPICIOUS_NEEDS_VERIFICATION: 'Suspicious — verify before proceeding',
      D_HIGH_RISK_SCAM: 'High-risk scam',
    },
  },
  vi: {
    title: 'Gửi báo cáo tới 165',
    step1: 'Bước 1 — Sao chép báo cáo',
    step2: 'Bước 2 — Mở biểu mẫu 165',
    step3: 'Bước 3 — Dán và điền thông tin cá nhân',
    step1Desc: 'Chúng tôi đã định dạng báo cáo. Sao chép và dán vào trường mô tả của biểu mẫu.',
    step2Desc: 'Nhấn bên dưới để mở biểu mẫu báo cáo trực tuyến chính thức 165 trong tab mới.',
    step3Desc: 'Dán báo cáo vào trường "mô tả", điền tên và số điện thoại của bạn, sau đó gửi.',
    copy: 'Sao chép báo cáo',
    copied: 'Đã sao chép!',
    openForm: 'Mở biểu mẫu báo cáo 165',
    preview: 'Xem trước báo cáo',
    close: 'Đóng',
    hint: 'Bạn cũng có thể gọi trực tiếp 165 — đường dây miễn phí 24h.',
    reportHeader: '=== VerifyFirst AI — Báo cáo lừa đảo ===',
    labelProb: 'Xác suất lừa đảo',
    labelVerdict: 'Phán quyết',
    labelConclusion: 'Kết luận',
    labelInput: 'Nội dung đáng ngờ',
    labelType: 'Loại đầu vào',
    labelSignals: 'Tín hiệu rủi ro phát hiện',
    labelTechInfo: 'Thông tin kỹ thuật (cho điều tra viên)',
    labelFinalUrl: 'URL đích cuối',
    labelRedirect: 'Chuỗi chuyển hướng',
    labelFooter: 'Được tạo bởi verify1st.tw',
    inputTypeMap: { URL: 'URL', SMS_TEXT: 'Tin nhắn', PHONE: 'Số điện thoại', IMAGE: 'Ảnh chụp' },
    verdictMap: {
      A_MARKETING: 'Marketing thông thường',
      B_RISKY_MARKETING: 'Marketing rủi ro',
      C_SUSPICIOUS_NEEDS_VERIFICATION: 'Đáng ngờ — cần xác minh',
      D_HIGH_RISK_SCAM: 'Lừa đảo nguy cơ cao',
    },
  },
} as const;

function buildReportText(analysis: TruthGuardAnalysis, t: typeof T['zh-TW']): string {
  const lines: string[] = [];

  lines.push(t.reportHeader);
  lines.push('');
  lines.push(`${t.labelProb}: ${analysis.scamProbability}%`);
  lines.push(`${t.labelVerdict}: ${t.verdictMap[analysis.finalVerdict as keyof typeof t.verdictMap] ?? analysis.finalVerdict}`);
  lines.push(`${t.labelConclusion}: ${analysis.conclusion ?? analysis.verdict ?? ''}`);
  lines.push('');
  lines.push(`${t.labelInput}:`);
  lines.push(analysis.originalInput);
  lines.push('');
  lines.push(`${t.labelType}: ${t.inputTypeMap[analysis.inputType as keyof typeof t.inputTypeMap] ?? analysis.inputType}`);
  lines.push('');

  if (analysis.riskSignals && analysis.riskSignals.length > 0) {
    lines.push(`${t.labelSignals}:`);
    for (const s of analysis.riskSignals) {
      lines.push(`  [${s.level}] ${s.type}: ${s.evidence}`);
    }
    lines.push('');
  }

  const av = analysis.agentVerification;
  if (av?.originalUrl || av?.finalLandingPage) {
    lines.push(`${t.labelTechInfo}:`);
    if (av.originalUrl) lines.push(`  ${t.labelInput}: ${av.originalUrl}`);
    if (av.finalLandingPage && av.finalLandingPage !== av.originalUrl) {
      lines.push(`  ${t.labelFinalUrl}: ${av.finalLandingPage}`);
    }
    if (av.redirectChain && av.redirectChain.length > 1) {
      lines.push(`  ${t.labelRedirect}: ${av.redirectChain.join(' → ')}`);
    }
    lines.push('');
  }

  lines.push(`${t.labelFooter} · ${new Date().toLocaleString()}`);
  return lines.join('\n');
}

const ReportModal: React.FC<ReportModalProps> = ({ analysis, language, onClose }) => {
  const t = T[language] ?? T['zh-TW'];
  const reportText = buildReportText(analysis, t as typeof T['zh-TW']);
  const [copied, setCopied] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  const backdropRef = useRef<HTMLDivElement>(null);

  // Auto-copy when modal opens
  useEffect(() => {
    navigator.clipboard.writeText(reportText).catch(() => {});
    setCopied(true);
    const timer = setTimeout(() => setCopied(false), 2500);
    return () => clearTimeout(timer);
  }, [reportText]);

  // Close on Escape
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', handleKey);
    return () => document.removeEventListener('keydown', handleKey);
  }, [onClose]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {}
  };

  const handleOpenForm = () => {
    window.open(REPORT_URL, '_blank', 'noopener,noreferrer');
  };

  return (
    <div
      ref={backdropRef}
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/70 backdrop-blur-sm px-0 sm:px-4"
      onClick={(e) => { if (e.target === backdropRef.current) onClose(); }}
    >
      <div className="relative w-full sm:max-w-lg bg-gray-900 border border-gray-700 rounded-t-3xl sm:rounded-2xl shadow-2xl max-h-[90vh] overflow-y-auto">

        {/* Header */}
        <div className="sticky top-0 z-10 bg-gray-900/95 backdrop-blur-sm border-b border-gray-800 flex items-center justify-between px-5 py-4 rounded-t-3xl sm:rounded-t-2xl">
          <div className="flex items-center gap-2">
            <Flag className="w-5 h-5 text-amber-400" />
            <h2 className="font-bold text-white text-base sm:text-lg">{t.title}</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors rounded-lg p-1"
            aria-label={t.close}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-5 space-y-5">

          {/* Step 1 — Copy */}
          <div className="flex gap-3">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-crypto-accent text-crypto-dark font-bold text-sm flex items-center justify-center">1</div>
            <div className="flex-1">
              <p className="font-semibold text-white text-sm mb-0.5">{t.step1}</p>
              <p className="text-gray-400 text-xs mb-3">{t.step1Desc}</p>
              <button
                onClick={handleCopy}
                className={`w-full flex items-center justify-center gap-2 py-3 rounded-xl font-bold text-sm transition-all ${
                  copied
                    ? 'bg-green-700 text-white'
                    : 'bg-crypto-accent text-crypto-dark hover:bg-white'
                }`}
              >
                {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? t.copied : t.copy}
              </button>

              {/* Preview toggle */}
              <button
                onClick={() => setPreviewOpen(prev => !prev)}
                className="mt-2 text-xs text-gray-500 hover:text-gray-300 transition-colors w-full text-left"
              >
                {previewOpen ? '▲' : '▼'} {t.preview}
              </button>
              {previewOpen && (
                <pre className="mt-2 bg-gray-950 border border-gray-800 rounded-lg p-3 text-xs text-gray-400 font-mono whitespace-pre-wrap break-all max-h-40 overflow-y-auto">
                  {reportText}
                </pre>
              )}
            </div>
          </div>

          {/* Step 2 — Open Form */}
          <div className="flex gap-3">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-amber-500 text-black font-bold text-sm flex items-center justify-center">2</div>
            <div className="flex-1">
              <p className="font-semibold text-white text-sm mb-0.5">{t.step2}</p>
              <p className="text-gray-400 text-xs mb-3">{t.step2Desc}</p>
              <button
                onClick={handleOpenForm}
                className="w-full flex items-center justify-center gap-2 py-3 rounded-xl font-bold text-sm bg-amber-500 hover:bg-amber-400 text-black transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                {t.openForm}
              </button>
            </div>
          </div>

          {/* Step 3 — Paste + fill */}
          <div className="flex gap-3">
            <div className="flex-shrink-0 w-7 h-7 rounded-full bg-gray-700 text-gray-300 font-bold text-sm flex items-center justify-center">3</div>
            <div className="flex-1">
              <p className="font-semibold text-white text-sm mb-0.5">{t.step3}</p>
              <p className="text-gray-400 text-xs">{t.step3Desc}</p>
            </div>
          </div>

          {/* Footer hint */}
          <p className="text-center text-xs text-gray-600 pt-2 border-t border-gray-800">
            📞 {t.hint}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ReportModal;
